### ISSUE TITLE
How to generate the dataset

### ISSUE THREAD

**Issue by YunqiuXu** [dylandjian/retro-contest-sonic#2]
Hi, is the method of generating datasets provided in this repository? If so (I noticed that there are files with name "jerk.py" and "human.py"), how can I run these code to get dataset?

Thanks for your help, looking forward to your response :D

**Comment by dylandjian** [comment]
Hello !

You have 2 ways of generating data : 
- using a random policy (which was done in the World Models paper) by modifying the play.py script and instead of launching a HumanGame, you launch a JerkGame 

- using a human recorded game to see the middle/end of the levels where the random policy would not be able to go. If you want to make this work, you have to download these games : https://github.com/openai/retro-movies/tree/master/human and put them in a folder called replay at the root of the repository (just like in the file human.py line 64/65). 

After that, you should be able to launch play.py if you have installed everything properly ! The results will be stored in a mongoDB database called "retro_contest", and the images will be saved (with pickle) in a collection called with the name of the timestamp you used to launch the program.

Let me know if you have any more issue !
